import { ChefHat, Clock3, Sparkles } from 'lucide-react'
import { Link } from 'react-router'
import { Button } from '../ui/button'

type Recipe = { id: string; title: string; description: string; time: number; match: number; ingredients: string[]; rescue: string; rescuedIngredients?: string[] }

export function RecipeCard({ recipe, compact = false }: { recipe: Recipe; compact?: boolean }) {
  const rescued = recipe.rescuedIngredients ?? []
  const missing = recipe.ingredients.filter((ingredient) => !rescued.includes(ingredient))
  return <article className={`flex ${compact ? 'h-[18rem]' : 'h-[36rem]'} flex-col overflow-hidden rounded-[1.5rem] border border-[#cde6ed] bg-white shadow-[0_8px_24px_rgba(31,78,93,0.06)]`}><div className={`relative flex ${compact ? 'h-20' : 'h-36'} shrink-0 items-center justify-center bg-[#e8f7fa] text-[#4f8ca3]`}><ChefHat size={compact ? 42 : 70} strokeWidth={1.3} /><span className="absolute left-4 top-4 inline-flex items-center gap-1 rounded-full bg-white/90 px-2.5 py-1 text-xs font-black text-[#145d72]"><Sparkles size={13} /> {recipe.match}% match</span><span className="absolute right-4 top-4 rounded-full bg-white/90 px-2.5 py-1 text-xs font-bold text-[#6f8b95]"><Clock3 size={13} className="mr-1 inline" /> {recipe.time} min</span></div><div className={`flex min-h-0 flex-1 flex-col ${compact ? 'p-3' : 'p-5'}`}><h2 className={`${compact ? 'text-base' : 'text-xl sm:text-2xl'} font-black text-[#173d4e]`}>{recipe.title}</h2><p className={`${compact ? 'mt-1 line-clamp-2 text-xs leading-4' : 'mt-2 text-sm leading-6'} text-[#6f8b95]`}>{recipe.description}</p><p className={`${compact ? 'mt-2' : 'mt-4'} text-xs font-bold uppercase tracking-[0.12em] text-[#bd6720]`}>{recipe.rescue}</p><div className={`${compact ? 'mt-2 gap-1' : 'mt-4 gap-2'} flex flex-1 flex-wrap content-start`}>{recipe.ingredients.map((ingredient) => <span key={ingredient} className={`rounded-full ${compact ? 'px-2 py-1 text-[10px]' : 'px-3 py-1.5 text-xs'} font-semibold ${rescued.includes(ingredient) ? 'bg-[#d9eef3] text-[#145d72]' : 'bg-[#f2f7f8] text-[#5e7f8b]'}`}>{ingredient}</span>)}</div>{!compact && rescued.length > 0 && <p className="mt-3 text-xs font-semibold text-[#145d72]">Rescues: {rescued.join(', ')}</p>}{!compact && missing.length > 0 && <p className="mt-1 text-xs text-[#6f8b95]">Still needed: {missing.join(', ')}</p>}<div className={`${compact ? 'mt-2' : 'mt-5'} grid grid-cols-2 gap-2`}><Button asChild className="h-10 bg-[#20bed0] text-xs text-[#063e4d] hover:bg-[#0db3c8]"><Link to={`/app/consumption?recipe=${encodeURIComponent(recipe.title)}`}><ChefHat size={14} /> Cook This</Link></Button><Button asChild variant="outline" className="h-10 border-[#b8d7de] bg-[#f0fafb] text-xs text-[#173d4e] hover:bg-white"><Link to={`/app/recipes/${recipe.id}`}>View recipe</Link></Button></div></div></article>
}
