import { Leaf, LockKeyhole, Mail, UserRound } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router'
import { Button } from '../components/ui/button'
import { login, register } from '../firebase/services/auth.service'

type AuthMode = 'login' | 'signup'

export function AuthPage() {
  const [mode, setMode] = useState<AuthMode>('login'); const [displayName, setDisplayName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  const navigate = useNavigate(); const signup = mode === 'signup'
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); setSubmitting(true); try { signup ? await register(email, password, displayName) : await login(email, password); navigate('/app') } catch { setError(signup ? 'We could not create your account. Check your details and try again.' : 'We could not sign you in. Check your email and password.') } finally { setSubmitting(false) } }
  return <main className="flex min-h-svh items-center justify-center bg-[#f8f7f2] px-5 py-8"><div className="grid w-full max-w-5xl overflow-hidden rounded-[2rem] border border-[#e5e1d5] bg-white shadow-[0_18px_50px_rgba(66,106,90,0.12)] lg:grid-cols-[0.9fr_1.1fr]"><section className="relative hidden overflow-hidden bg-gradient-to-br from-[#426a5a] via-[#355747] to-[#2d493d] p-10 text-white lg:flex lg:min-h-[620px] lg:flex-col lg:justify-between"><div className="absolute -bottom-24 -left-16 size-72 rounded-full border-[32px] border-[#dce9de]/30" /><div className="relative"><Link to="/" className="text-sm font-black tracking-[0.18em] text-[#f8dda6]">FRESHVII</Link><Leaf className="mt-20 text-[#f2c57c]" size={42} /><h1 className="mt-6 max-w-sm text-5xl font-black leading-[1.05]">Make room for good food.</h1><p className="mt-5 max-w-sm leading-7 text-[#dce9de]">Your personal kitchen companion for fresher choices, less waste, and easier meals.</p></div><p className="relative text-sm text-[#dce9de]">Track it. Rescue it. Enjoy it.</p></section><section className="p-6 sm:p-10 lg:p-14"><div className="mb-8 lg:hidden"><Link to="/" className="text-sm font-black tracking-[0.18em] text-[#426a5a]">FRESHVII</Link></div><div className="mb-8"><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#426a5a]">Your kitchen, in sync</p><h2 className="mt-2 text-3xl font-black text-[#2d493d]">{signup ? 'Create your account' : 'Welcome back'}</h2><p className="mt-3 text-[#7d806e]">{signup ? 'Start keeping good food in rotation.' : 'Pick up where your kitchen left off.'}</p></div><div className="mb-7 grid grid-cols-2 rounded-2xl bg-[#dce9de] p-1"><Tab active={!signup} onClick={() => { setMode('login'); setError('') }}>Sign in</Tab><Tab active={signup} onClick={() => { setMode('signup'); setError('') }}>Create account</Tab></div><form onSubmit={submit} className="space-y-5">{signup && <Field label="Your name" icon={<UserRound size={18} />}><input required value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="Alex Morgan" /></Field>}<Field label="Email address" icon={<Mail size={18} />}><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" /></Field><Field label="Password" icon={<LockKeyhole size={18} />}><input required minLength={6} type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="At least 6 characters" /></Field>{error && <p role="alert" className="rounded-xl bg-[#f9ddd9] px-4 py-3 text-sm text-[#7c3733]">{error}</p>}<Button disabled={submitting} className="h-12 w-full bg-[#426a5a] text-base text-white hover:bg-[#355747]">{submitting ? 'Working...' : signup ? 'Create my account' : 'Sign in to FRESHVII'}</Button></form><p className="mt-7 text-center text-xs text-[#7d806e]">By continuing, you agree to keep your food data private and yours.</p></section></div></main>
}
function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" onClick={onClick} className={`rounded-xl px-4 py-3 text-sm font-bold ${active ? 'bg-white text-[#426a5a] shadow-sm' : 'text-[#61755e]'}`}>{children}</button> }
function Field({ label, icon, children }: { label: string; icon: React.ReactNode; children: React.ReactNode }) { return <label className="block"><span className="mb-2 block text-sm font-bold text-[#2d493d]">{label}</span><span className="flex items-center gap-3 rounded-xl border border-[#e5e1d5] bg-[#fdfbf6] px-4 text-[#7d806e] focus-within:border-[#426a5a]">{icon}{children}</span></label> }
