import { ArrowLeft, CalendarDays, Snowflake, Trash2, Utensils } from 'lucide-react'
import { Link, useParams } from 'react-router'
import { FreshnessBadge } from '../components/food/FreshnessBadge'
import { Button } from '../components/ui/button'
import { foodItems } from '../data/mockData'

export function FoodDetailPage() {
  const { foodId } = useParams()
  const item = foodItems.find((food) => food.id === foodId) ?? foodItems[0]
  return <div className="w-full max-w-4xl space-y-8"><Link to="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#426a5a]"><ArrowLeft size={16} /> Back to kitchen</Link><section className="grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><div className="flex min-h-64 items-center justify-center rounded-[2rem]" style={{ backgroundColor: item.accent }}><Utensils size={80} className="text-stone-700/60" /></div><div className="rounded-[2rem] border border-[#e5e1d5] bg-white p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-bold uppercase tracking-[0.14em] text-stone-500">{item.category}</p><FreshnessBadge state={item.freshness} /></div><h1 className="mt-3 text-4xl font-black">{item.name}</h1><p className="mt-3 text-stone-600">{item.quantity} {item.unit} · {item.location} · {item.opened ? 'Opened' : 'Sealed'}</p><div className="mt-8 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#f6f1e5] p-4"><CalendarDays size={18} className="text-[#426a5a]" /><p className="mt-3 text-xs font-bold uppercase text-stone-500">Best used</p><p className="mt-1 font-bold">{item.expires}</p></div><div className="rounded-2xl bg-[#f6f1e5] p-4"><Snowflake size={18} className="text-[#426a5a]" /><p className="mt-3 text-xs font-bold uppercase text-stone-500">Rescue score</p><p className="mt-1 font-bold">{item.rescueScore}/100</p></div></div><div className="mt-8 flex flex-wrap gap-3"><Button className="bg-[#426a5a] text-white hover:bg-[#355747]"><Utensils size={17} /> Use some</Button><Button variant="outline"><Snowflake size={17} /> Freeze it</Button><Button variant="destructive"><Trash2 size={17} /> Discard</Button></div></div></section><section className="rounded-[2rem] border border-[#e5e1d5] bg-white p-6"><h2 className="text-xl font-black">Freshness timeline</h2><div className="mt-6 space-y-5 border-l-2 border-[#dce9de] pl-5 text-sm"><div><p className="font-bold">Added to your kitchen</p><p className="text-stone-500">April 18 · {item.location}</p></div><div><p className="font-bold">{item.opened ? 'Opened and freshness recalculated' : 'Still sealed'}</p><p className="text-stone-500">Current state is based on storage and estimated expiry.</p></div></div></section></div>
}
