import { ArrowRight, Flame, Lightbulb } from 'lucide-react'
import { Link } from 'react-router'
import { FreshnessBadge } from '../components/food/FreshnessBadge'
import { foodItems } from '../data/mockData'

export function RescuePage() {
  const urgent = foodItems.filter((item) => item.rescueScore > 40).sort((a, b) => b.rescueScore - a.rescueScore)
  return <div className="w-full max-w-4xl space-y-8"><div><p className="flex items-center gap-2 text-sm font-bold uppercase tracking-[0.14em] text-[#b84f49]"><Flame size={16} /> Food rescue</p><h1 className="mt-2 text-4xl font-black tracking-tight">Rescue my food</h1><p className="mt-3 max-w-xl text-stone-600">A short list of what deserves your attention first, ranked by urgency, quantity, and recipe potential.</p></div><div className="flex items-start gap-3 rounded-3xl bg-[#f9ddd9] p-5 text-[#7c3733]"><Lightbulb size={20} className="mt-0.5 shrink-0" /><p className="text-sm leading-6"><strong>Small win:</strong> using the spinach today prevents the highest-risk item from becoming waste.</p></div><div className="space-y-3">{urgent.map((item, index) => <Link key={item.id} to={`/food/${item.id}`} className="group flex items-center gap-4 rounded-3xl border border-[#e5e1d5] bg-white p-4 transition-transform hover:-translate-y-0.5 sm:p-5"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-[#f6e8c9] text-sm font-black text-[#9b6c22]">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{item.name}</h2><FreshnessBadge state={item.freshness} /></div><p className="mt-1 text-sm text-stone-500">{item.quantity} {item.unit} remaining · {item.expires} · {item.category}</p></div><div className="text-right"><p className="text-2xl font-black text-[#b84f49]">{item.rescueScore}</p><p className="text-[11px] font-bold uppercase text-stone-400">score</p></div><ArrowRight size={18} className="text-stone-400" /></Link>)}</div></div>
}
